# Generated by Django 6.0.5 on 2026-05-08 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('nro_reg', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nº Registro')),
                ('data_nasc', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('idade', models.CharField(blank=True, default='', max_length=50)),
                ('marcacao_1', models.CharField(blank=True, default='', max_length=100, verbose_name='Marcação 1')),
                ('marcacao_2', models.CharField(blank=True, default='', max_length=100, verbose_name='Marcação 2')),
                ('apelido', models.CharField(blank=True, default='', max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea'), ('I', 'Indeterminado')], default='I', max_length=1)),
                ('plantel', models.CharField(blank=True, default='', max_length=100)),
                ('nro_gefau', models.CharField(blank=True, default='', max_length=50, verbose_name='Nº GEFAU')),
                ('nro_livro', models.CharField(blank=True, default='', max_length=50, verbose_name='Nº Livro')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'ordering': ['apelido'],
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cientifico', models.CharField(max_length=200, unique=True)),
                ('nome_comum', models.CharField(max_length=200)),
                ('grupo_taxonomico', models.CharField(max_length=100)),
                ('plano_manejo', models.TextField(blank=True, default='')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('status_conservacao', models.CharField(choices=[('LC', 'Menos Preocupante'), ('NT', 'Quase Ameaçada'), ('VU', 'Vulnerável'), ('EN', 'Em Perigo'), ('CR', 'Criticamente em Perigo'), ('EW', 'Extinta na Natureza'), ('EX', 'Extinta')], default='LC', max_length=2)),
            ],
            options={
                'verbose_name': 'Espécie',
                'verbose_name_plural': 'Espécies',
                'ordering': ['nome_comum'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(blank=True, default='', max_length=20)),
                ('funcao', models.CharField(max_length=100, verbose_name='Função')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Recinto',
            fields=[
                ('recinto_gefau', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cap_maxima', models.PositiveIntegerField(verbose_name='Capacidade Máxima')),
                ('qnt_animais', models.PositiveIntegerField(default=0, verbose_name='Quantidade de Animais')),
                ('qnt_especies', models.PositiveIntegerField(default=0, verbose_name='Quantidade de Espécies')),
            ],
            options={
                'verbose_name': 'Recinto',
                'verbose_name_plural': 'Recintos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Casal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casais_como_1', to='core.animal')),
                ('animal_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casais_como_2', to='core.animal')),
            ],
            options={
                'verbose_name': 'Casal',
                'verbose_name_plural': 'Casais',
            },
        ),
        migrations.CreateModel(
            name='DescricaoRotina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_rotina', models.CharField(choices=[('programa', 'Programa'), ('cardapio', 'Cardápio'), ('condicionamento', 'Condicionamento'), ('enriquecimento', 'Enriquecimento')], max_length=20)),
                ('objetivo', models.TextField(blank=True, default='')),
                ('metodologia', models.TextField(blank=True, default='')),
                ('ferramentas', models.TextField(blank=True, default='')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotinas', to='core.animal')),
            ],
            options={
                'verbose_name': 'Descrição de Rotina',
                'verbose_name_plural': 'Descrições de Rotina',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=100)),
                ('nro_documento', models.CharField(max_length=100)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('data', models.DateField()),
                ('observacao', models.TextField(blank=True, default='')),
                ('tipo_migracao', models.CharField(blank=True, choices=[('baixa', 'Baixa'), ('entrada', 'Entrada')], default='', max_length=10)),
                ('destino', models.CharField(blank=True, default='', max_length=200)),
                ('origem', models.CharField(blank=True, default='', max_length=200)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.animal')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animais', to='core.especie'),
        ),
        migrations.CreateModel(
            name='ItemCardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimento', models.CharField(max_length=200)),
                ('qnt_porcao', models.CharField(max_length=100, verbose_name='Quantidade da Porção')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('frequencia', models.CharField(blank=True, default='', max_length=100, verbose_name='Frequência')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardapio', to='core.animal')),
            ],
            options={
                'verbose_name': 'Item de Cardápio',
                'verbose_name_plural': 'Itens de Cardápio',
            },
        ),
        migrations.CreateModel(
            name='Prole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mae', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prole_como_mae', to='core.animal')),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prole_como_pai', to='core.animal')),
                ('prole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prole_como_filho', to='core.animal')),
            ],
            options={
                'verbose_name': 'Prole',
                'verbose_name_plural': 'Proles',
            },
        ),
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField()),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('motivo_saida', models.TextField(blank=True, default='')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='core.animal')),
                ('recinto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='core.recinto')),
            ],
            options={
                'verbose_name': 'Alocação',
                'verbose_name_plural': 'Alocações',
                'ordering': ['-data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('data_hora', models.DateTimeField()),
                ('ocorrencia', models.TextField(verbose_name='Ocorrência')),
                ('tipo_registro', models.CharField(choices=[('clinico', 'Clínico'), ('biologico', 'Biológico')], max_length=10)),
                ('detalhamento', models.TextField(blank=True, default='')),
                ('anexo_laudo_saude', models.FileField(blank=True, null=True, upload_to='laudos/')),
                ('tratamento', models.TextField(blank=True, default='')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='core.animal')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='core.funcionario')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='MedicacaoAdministrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=200)),
                ('dose_pv', models.CharField(max_length=100, verbose_name='Dose PV')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicacoes', to='core.registro')),
            ],
            options={
                'verbose_name': 'Medicação Administrada',
                'verbose_name_plural': 'Medicações Administradas',
            },
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(max_length=100)),
                ('resultado', models.TextField(blank=True, default='')),
                ('observacao', models.TextField(blank=True, default='')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames', to='core.registro')),
            ],
            options={
                'verbose_name': 'Exame',
                'verbose_name_plural': 'Exames',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='RegistroRotina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_rotina', models.CharField(max_length=100)),
                ('data_horario', models.DateTimeField()),
                ('observacoes', models.TextField(blank=True, default='')),
                ('dia_semana', models.CharField(blank=True, default='', max_length=20)),
                ('frequencia', models.CharField(blank=True, default='', max_length=100)),
                ('tipo', models.CharField(blank=True, default='', max_length=100)),
                ('comandos', models.TextField(blank=True, default='')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_rotina', to='core.animal')),
            ],
            options={
                'verbose_name': 'Registro de Rotina',
                'verbose_name_plural': 'Registros de Rotina',
            },
        ),
        migrations.CreateModel(
            name='Restricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('restricao', models.TextField(verbose_name='Restrição')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricoes', to='core.animal')),
            ],
            options={
                'verbose_name': 'Restrição',
                'verbose_name_plural': 'Restrições',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Risco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('risco', models.TextField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riscos', to='core.animal')),
            ],
            options={
                'verbose_name': 'Risco',
                'verbose_name_plural': 'Riscos',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Triagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('peso_ao_chegar', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('score_corporal', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('gravidade_veterinaria', models.CharField(blank=True, default='', max_length=100)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('idade_na_triagem', models.CharField(blank=True, default='', max_length=50)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triagens', to='core.animal')),
            ],
            options={
                'verbose_name': 'Triagem',
                'verbose_name_plural': 'Triagens',
                'ordering': ['-data'],
            },
        ),
    ]
