-- 1. Tabelas Folhas (Não possuem nenhuma outra tabela dependendo delas)
DROP TABLE PROLE;
DROP TABLE EXAMES;
DROP TABLE MEDICAMENTOADMINISTRADO;
DROP TABLE RESTRICOES;
DROP TABLE RISCO;
DROP TABLE REGISTROBIOLOGICO;
DROP TABLE REGISTROROTINA;
DROP TABLE ITEMCARDAPIO;
DROP TABLE DOCUMENTO;
DROP TABLE ALOCACAO;

-- 2. Tabelas Intermediárias (Dependem das tabelas raízes, mas são pais das tabelas folhas)
DROP TABLE CASAL;
DROP TABLE REGISTROCLINICO;
DROP TABLE DESCRICAOROTINA;
DROP TABLE TRIAGEM;

-- 3. Tabelas Raízes/Base (Não dependem de ninguém, foram as primeiras a serem criadas)
DROP TABLE ANIMAL;
DROP TABLE ESPECIE;
DROP TABLE RECINTO;
DROP TABLE FUNCIONARIO;